import pandas as pd
df = pd.read_json("G:\Project\BrickView\Scripts\listings.json")
df["Date_Listed"] = pd.to_datetime(df["Date_Listed"])
df.to_csv("G:\Project\BrickView\Scripts\listings.csv")
df1 = pd.read_json("G:\Project\BrickView\Scripts\property.json")
df1.to_csv("G:\Project\BrickView\Scripts\property.csv")
df2 = pd.read_json("G:\Project\BrickView\Scripts\Agents.json")
df2.to_csv("G:\Project\BrickView\Scripts\Agents.csv")
df3= pd.read_json("G:\Project\BrickView\Scripts\Buyers.json")
df3["loan_provider"] = df3["loan_provider"].fillna("No Loan")
df3.to_csv("G:\Project\BrickView\Scripts\Buyers.csv")
df4=pd.read_csv("G:\Project\BrickView\Scripts\sales.csv")
df4["Date_Sold"] = pd.to_datetime(df4["Date_Sold"])
df4.to_csv("G:\Project\BrickView\Scripts\sales_cleaned.csv")